version: "3.8"

services:
  db:
    image: postgres:15.3-alpine
    container_name: ${POSTGRES_HOST}
    env_file:
      - test/integration/.env
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - go-url-shortener-test
    
  redis:
    build:
      context: .
      dockerfile: dockerconfig/redis/Dockerfile
    container_name: ${REDIS_HOST}
    env_file:
      - test/integration/.env
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - go-url-shortener-test
    
  zookeeper:
    build:
      context: .
      dockerfile: dockerconfig/zookeeper/Dockerfile
    container_name: ${ZOOKEEPER_HOST}
    env_file:
      - test/integration/.env
    ports:
      - "2181:2181"
    networks:
      - go-url-shortener-test

networks:
  go-url-shortener-test:
    driver: bridge
