version: "3.8"

services:
  db:
    image: postgres:alpine
    container_name: go-url-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=short_url
    ports:
      - 5432:5432
    volumes:
      - go-url-db:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: build/Dockerfile
    container_name: go-url-shortener
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    command: sh -c "/app/scripts/wait-for-it.sh go-url-db:5432 -t 60 -- ./app migrate && ./app server"

  redis:
    container_name: go-url-cache
    image: redis
    ports:
      - 6379:6379

volumes:
  go-url-db:
