// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.25.0
// source: urlshortner.proto

package UrlShortner

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShrotUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LongUrl string `protobuf:"bytes,1,opt,name=longUrl,proto3" json:"longUrl,omitempty"`
}

func (x *ShrotUrlRequest) Reset() {
	*x = ShrotUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_urlshortner_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShrotUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShrotUrlRequest) ProtoMessage() {}

func (x *ShrotUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urlshortner_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShrotUrlRequest.ProtoReflect.Descriptor instead.
func (*ShrotUrlRequest) Descriptor() ([]byte, []int) {
	return file_urlshortner_proto_rawDescGZIP(), []int{0}
}

func (x *ShrotUrlRequest) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

type ShortUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=shortUrl,proto3" json:"shortUrl,omitempty"`
}

func (x *ShortUrlResponse) Reset() {
	*x = ShortUrlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_urlshortner_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortUrlResponse) ProtoMessage() {}

func (x *ShortUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urlshortner_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortUrlResponse.ProtoReflect.Descriptor instead.
func (*ShortUrlResponse) Descriptor() ([]byte, []int) {
	return file_urlshortner_proto_rawDescGZIP(), []int{1}
}

func (x *ShortUrlResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type LongUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=shortUrl,proto3" json:"shortUrl,omitempty"`
}

func (x *LongUrlRequest) Reset() {
	*x = LongUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_urlshortner_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LongUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongUrlRequest) ProtoMessage() {}

func (x *LongUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_urlshortner_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongUrlRequest.ProtoReflect.Descriptor instead.
func (*LongUrlRequest) Descriptor() ([]byte, []int) {
	return file_urlshortner_proto_rawDescGZIP(), []int{2}
}

func (x *LongUrlRequest) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type LongUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LongUrl string `protobuf:"bytes,1,opt,name=longUrl,proto3" json:"longUrl,omitempty"`
}

func (x *LongUrlResponse) Reset() {
	*x = LongUrlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_urlshortner_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LongUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongUrlResponse) ProtoMessage() {}

func (x *LongUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_urlshortner_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongUrlResponse.ProtoReflect.Descriptor instead.
func (*LongUrlResponse) Descriptor() ([]byte, []int) {
	return file_urlshortner_proto_rawDescGZIP(), []int{3}
}

func (x *LongUrlResponse) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

var File_urlshortner_proto protoreflect.FileDescriptor

var file_urlshortner_proto_rawDesc = []byte{
	0x0a, 0x11, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x6e, 0x65, 0x72,
	0x22, 0x2b, 0x0a, 0x0f, 0x53, 0x68, 0x72, 0x6f, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x22, 0x2e, 0x0a,
	0x10, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x2c, 0x0a,
	0x0e, 0x4c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x2b, 0x0a, 0x0f, 0x4c,
	0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x32, 0xad, 0x01, 0x0a, 0x12, 0x55, 0x72, 0x6c,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x4c, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x1c,
	0x2e, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x72,
	0x6f, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x75,
	0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a,
	0x0a, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x12, 0x1b, 0x2e, 0x75, 0x72,
	0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x6e, 0x67, 0x55, 0x72,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x3b, 0x55,
	0x72, 0x6c, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_urlshortner_proto_rawDescOnce sync.Once
	file_urlshortner_proto_rawDescData = file_urlshortner_proto_rawDesc
)

func file_urlshortner_proto_rawDescGZIP() []byte {
	file_urlshortner_proto_rawDescOnce.Do(func() {
		file_urlshortner_proto_rawDescData = protoimpl.X.CompressGZIP(file_urlshortner_proto_rawDescData)
	})
	return file_urlshortner_proto_rawDescData
}

var file_urlshortner_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_urlshortner_proto_goTypes = []interface{}{
	(*ShrotUrlRequest)(nil),  // 0: urlshortner.ShrotUrlRequest
	(*ShortUrlResponse)(nil), // 1: urlshortner.ShortUrlResponse
	(*LongUrlRequest)(nil),   // 2: urlshortner.LongUrlRequest
	(*LongUrlResponse)(nil),  // 3: urlshortner.LongUrlResponse
}
var file_urlshortner_proto_depIdxs = []int32{
	0, // 0: urlshortner.UrlShortnerService.GetShortUrl:input_type -> urlshortner.ShrotUrlRequest
	2, // 1: urlshortner.UrlShortnerService.GetLongUrl:input_type -> urlshortner.LongUrlRequest
	1, // 2: urlshortner.UrlShortnerService.GetShortUrl:output_type -> urlshortner.ShortUrlResponse
	3, // 3: urlshortner.UrlShortnerService.GetLongUrl:output_type -> urlshortner.LongUrlResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_urlshortner_proto_init() }
func file_urlshortner_proto_init() {
	if File_urlshortner_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_urlshortner_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShrotUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_urlshortner_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortUrlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_urlshortner_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LongUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_urlshortner_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LongUrlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_urlshortner_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_urlshortner_proto_goTypes,
		DependencyIndexes: file_urlshortner_proto_depIdxs,
		MessageInfos:      file_urlshortner_proto_msgTypes,
	}.Build()
	File_urlshortner_proto = out.File
	file_urlshortner_proto_rawDesc = nil
	file_urlshortner_proto_goTypes = nil
	file_urlshortner_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UrlShortnerServiceClient is the client API for UrlShortnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UrlShortnerServiceClient interface {
	GetShortUrl(ctx context.Context, in *ShrotUrlRequest, opts ...grpc.CallOption) (*ShortUrlResponse, error)
	GetLongUrl(ctx context.Context, in *LongUrlRequest, opts ...grpc.CallOption) (*LongUrlResponse, error)
}

type urlShortnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUrlShortnerServiceClient(cc grpc.ClientConnInterface) UrlShortnerServiceClient {
	return &urlShortnerServiceClient{cc}
}

func (c *urlShortnerServiceClient) GetShortUrl(ctx context.Context, in *ShrotUrlRequest, opts ...grpc.CallOption) (*ShortUrlResponse, error) {
	out := new(ShortUrlResponse)
	err := c.cc.Invoke(ctx, "/urlshortner.UrlShortnerService/GetShortUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urlShortnerServiceClient) GetLongUrl(ctx context.Context, in *LongUrlRequest, opts ...grpc.CallOption) (*LongUrlResponse, error) {
	out := new(LongUrlResponse)
	err := c.cc.Invoke(ctx, "/urlshortner.UrlShortnerService/GetLongUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UrlShortnerServiceServer is the server API for UrlShortnerService service.
type UrlShortnerServiceServer interface {
	GetShortUrl(context.Context, *ShrotUrlRequest) (*ShortUrlResponse, error)
	GetLongUrl(context.Context, *LongUrlRequest) (*LongUrlResponse, error)
}

// UnimplementedUrlShortnerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUrlShortnerServiceServer struct {
}

func (*UnimplementedUrlShortnerServiceServer) GetShortUrl(context.Context, *ShrotUrlRequest) (*ShortUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShortUrl not implemented")
}
func (*UnimplementedUrlShortnerServiceServer) GetLongUrl(context.Context, *LongUrlRequest) (*LongUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLongUrl not implemented")
}

func RegisterUrlShortnerServiceServer(s *grpc.Server, srv UrlShortnerServiceServer) {
	s.RegisterService(&_UrlShortnerService_serviceDesc, srv)
}

func _UrlShortnerService_GetShortUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShrotUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlShortnerServiceServer).GetShortUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/urlshortner.UrlShortnerService/GetShortUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlShortnerServiceServer).GetShortUrl(ctx, req.(*ShrotUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrlShortnerService_GetLongUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LongUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlShortnerServiceServer).GetLongUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/urlshortner.UrlShortnerService/GetLongUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlShortnerServiceServer).GetLongUrl(ctx, req.(*LongUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UrlShortnerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "urlshortner.UrlShortnerService",
	HandlerType: (*UrlShortnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetShortUrl",
			Handler:    _UrlShortnerService_GetShortUrl_Handler,
		},
		{
			MethodName: "GetLongUrl",
			Handler:    _UrlShortnerService_GetLongUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "urlshortner.proto",
}
