http:
  port: 3000
postgres:
  dsn: "host=go-url-shortener-db user=postgres password=postgres dbname=go-url-shortener port=5432 sslmode=disable TimeZone=UTC"
redis:
  cluster_mode: false
  host: "go-url-shortener-redis"
  port: 6379
  password:
  max_retries: 1
  pool_size_per_node: 2
  db: 2
  dial_timeout: 15s
