http:
  port: 8080
postgres:
  dsn: "host=go-url-db user=postgres password=postgres dbname=short_url port=5432 sslmode=disable TimeZone=UTC"
redis:
  cluster_mode: false
  host: "go-url-cache"
  port: 6379
  password:
  max_retries: 1
  pool_size_per_node: 2
  db: 2
  dial_timeout: 15s
