// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"go-url-shortener/config"
	"go-url-shortener/internal/delivery"
)

// Injectors from wire.go:

func Initialize() (Application, error) {
	httpServer := delivery.NewHttpServer()
	configConfig, err := config.New()
	if err != nil {
		return Application{}, err
	}
	application := NewApplication(httpServer, configConfig)
	return application, nil
}
