// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"go-url-shortener/internal/delivery/handler"
	"go-url-shortener/internal/repository"
	"go-url-shortener/internal/usecase/shorturl"
	"go-url-shortener/pkg/postgres"
	"go-url-shortener/pkg/redis"
)

// Injectors from wire.go:

func Initialize() (Application, error) {
	postgresPostgres, err := postgres.NewPostgres()
	if err != nil {
		return Application{}, err
	}
	shortUrlRepository := repository.NewShortUrlRepo(postgresPostgres)
	redisClient, err := redis.InitClient()
	if err != nil {
		return Application{}, err
	}
	shortUrlUsecase := shorturl.NewShortUrlUsecase(shortUrlRepository, redisClient)
	shortUrlHandler := handler.NewShortUrlHandler(shortUrlUsecase)
	application := NewApplication(shortUrlHandler)
	return application, nil
}
