name: Go Test with Coverage

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: Run Tests with Coverage
      run: go test -v -coverprofile=coverage.txt -cover ./test/...
    - name: Upload Coverage Artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage.txt
